import ExcelJS from "exceljs";

export async function exportExcel(data, extraColumns = [], { metadata, options } = {}) {
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet("DSA Sheet");

    const baseColumns = [
        { header: "Topic", key: "topic", width: 20 },
        { header: "Problem", key: "problem", width: 40 },
        { header: "Link", key: "link", width: 50 },
        { header: "Difficulty", key: "difficulty", width: 15 }
    ];

    let additionalCols = extraColumns.map(col => ({
        header: col,
        key: col.toLowerCase().replace(/\s+/g, '_'),
        width: 20
    }));

    // Feature: Progress Tracking
    if (options && options.includeProgress) {
        additionalCols = [
            { header: "Status", key: "status", width: 15 },
            { header: "Notes", key: "notes", width: 30 },
            { header: "Last Revised", key: "last_revised", width: 15 },
            ...additionalCols
        ];
    }

    // 1. Define Columns (This sets the header row at row 1 initially)
    sheet.columns = [...baseColumns, ...additionalCols];

    // Data Rows
    const rows = data.map(p => {
        const row = {
            topic: p.topic,
            problem: p.title || p.name,
            link: p.links?.leetcode || p.links?.article || "",
            difficulty: p.difficulty
        };
        // Initialize extra/progress columns
        additionalCols.forEach(col => {
            row[col.key] = "";
        });
        return row;
    });

    sheet.addRows(rows);

    // 2. Insert Metadata Rows at the top (pushing everything down)
    if (metadata) {
        sheet.insertRow(1, []); // Spacer
        sheet.insertRow(1, [`Generated by PrepExport`]);
        sheet.insertRow(1, [`Author: ${metadata.author} | Version: ${metadata.version}`]);
        sheet.insertRow(1, [`Source: ${metadata.label}`]);

        // Merge metadata cells for better view
        sheet.mergeCells('A1:D1');
        sheet.mergeCells('A2:D2');
        sheet.mergeCells('A3:D3');
    }

    // Calculate significant rows
    const headerRowIdx = metadata ? 5 : 1;
    const firstDataRowIdx = headerRowIdx + 1;
    const lastDataRowIdx = headerRowIdx + rows.length;

    // 3. Style Header Row
    const headerRow = sheet.getRow(headerRowIdx);
    headerRow.font = { bold: true };
    headerRow.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFFFE0B2' } // Light Orange/Yellow
    };
    headerRow.commit(); // helpful for streamed writing, good practice

    // 4. Style Extra Columns
    // baseColumns.length is the start index for extra columns (0-based in array, 1-based in Excel)
    const extraColStartIdx = baseColumns.length + 1;
    const totalCols = baseColumns.length + additionalCols.length;

    if (additionalCols.length > 0) {
        for (let c = extraColStartIdx; c <= totalCols; c++) {
            // Apply style to the header of extra column
            const cell = headerRow.getCell(c);
            cell.fill = {
                type: 'pattern',
                pattern: 'solid',
                fgColor: { argb: 'A9A9A9' } // Light Purple for distinction
            };

            // Apply style to data cells in these columns
            for (let r = firstDataRowIdx; r <= lastDataRowIdx; r++) {
                const dataCell = sheet.getRow(r).getCell(c);
                dataCell.fill = {
                    type: 'pattern',
                    pattern: 'solid',
                    fgColor: { argb: '808080' } // Very light purple
                };
            }
        }
    }

    // 5. Branding Footer
    const footerRowIdx = lastDataRowIdx + 2;
    const footerRow = sheet.getRow(footerRowIdx);
    footerRow.getCell(1).value = "Exported with PrepExport - https://pre-export.vercel.app/";
    footerRow.font = { italic: true, color: { argb: 'FF888888' } };
    sheet.mergeCells(`A${footerRowIdx}:D${footerRowIdx}`);

    const buffer = await workbook.xlsx.writeBuffer();
    return { buffer, contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", extension: "xlsx" };
}
